import Head from "next/head";
import { MyPageProfile, MyPagePortfolioList } from "@/components";
import { MyPageLayout } from "@/layouts";
import { useMyPortfolioList } from "@/models/portfolio";
import useUser from "@/hooks/useUser";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const { list: myPortfolioList } = useMyPortfolioList();
  const { user: userInfo, isLogined } = useUser();

  if (!isLogined) return router.push("/");

  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPageLayout
        profile={<MyPageProfile userInfo={userInfo} />}
        portfiloList={<MyPagePortfolioList myPortfolioList={myPortfolioList} />}
      />
    </div>
  );
}
