import Head from "next/head";
import { MyPageProfile, MyPagePortfolioList } from "@/components";
import { MyPageLayout } from "@/layouts";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPageLayout
        profile={<MyPageProfile />}
        portfiloList={<MyPagePortfolioList />}
      />
    </div>
  );
}
