import Head from "next/head";
import { useEffect } from "react";
import SignupPopupView from "@/components/common/Auth/SignupPopup";
import useModal from "@/hooks/useModal";

function Home() {
  const { openModal } = useModal();

  useEffect(() => {
    openModal({
      title: "회원가입을 위해 아래의 정보를 입력해주세요.",
      content: <SignupPopupView />,
      menualClose: true,
    });
  }, [openModal]);

  return (
    <div>
      <Head>
        <title>BSSM SH - 회원가입</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export default function Page() {
  return <Home />;
}
