import { HeaderButton } from "@/components";
import { MainLayout } from "@/layouts";
import Head from "next/head";
import { SubmitHandler, useForm } from "react-hook-form";

interface SigninForm {
  username: string;
  password: string;
}

function Home() {
  const { register, handleSubmit } = useForm<SigninForm>();
  const onSubmit: SubmitHandler<SigninForm> = (data) => data;

  return (
    <div>
      <Head>
        <title>BSSM SH - 로그인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>로그인 페이지 입니다.</h1>
      <form className="flex flex-col" onSubmit={handleSubmit(onSubmit)}>
        <input
          className="border-2"
          placeholder="username"
          {...register("username")}
        />
        <input
          className="border-2"
          placeholder="password"
          {...register("password")}
        />
      </form>
      <div className="flex flex-col items-start">
        <HeaderButton>Google Login</HeaderButton>
        <HeaderButton>Naver Login</HeaderButton>
      </div>
    </div>
  );
}

export default function Page() {
  return <div />;
}
