import DataGrid from "@/components/contents/DataGrid";
import DataGridTitle from "@/components/contents/DatagridTitle";
import ChannelContentLayout from "@/layouts/ChannelContent";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChannelContentLayout title={<DataGridTitle />} datagrid={<DataGrid />} />
    </div>
  );
}
