import Head from "next/head";
import { AppLayout } from "@/layouts";
import {
  AppComment,
  AppDetail,
  PortfolioPlayer,
  AppSideMenu,
} from "@/components";
import type { GetServerSideProps } from "next";
import httpClient from "@/apis";
import { Portfolio } from "@/types/portfolio.interface";
import { getFileDownloadUrl } from "@/utils/file";
import { getDateParsedData } from "@/utils/date";

interface PortfolioIdPageProps {
  portfolio: Portfolio;
}

export default function Home({ portfolio }: PortfolioIdPageProps) {
  const dateParsedPortfolio: Portfolio = getDateParsedData(portfolio);
  const type = dateParsedPortfolio.portfolioType;

  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout
        app={
          <PortfolioPlayer
            url={
              type === "VIDEO"
                ? getFileDownloadUrl(dateParsedPortfolio.video)
                : dateParsedPortfolio.portfolioUrl
            }
            type={type}
          />
        }
        sidebar={<AppSideMenu />}
        detail={<AppDetail portfolio={dateParsedPortfolio} />}
        comment={<AppComment />}
      />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { id } = context.query;
  if (Number.isNaN(Number(id)))
    return {
      notFound: true,
    };

  const portfolio = (await httpClient.portfolio.getById({ params: { id } }))
    .data;

  return {
    props: {
      portfolio: JSON.parse(JSON.stringify(portfolio)),
    },
  };
};
