import Filter from "@/components/contents/Filter";
import PortfolioList from "@/components/portfolio/PortfolioList";
import SearchPageLayout from "@/layouts/Search";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function SearchPage() {
  const router = useRouter();
  const [keyword, setKeyword] = useState<string>("");

  useEffect(() => {
    setKeyword((router.query.keyword as string) || "");
  }, [router.query]);

  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchPageLayout
        filter={<Filter />}
        portfolioList={<PortfolioList keyword={keyword} />}
      />
    </div>
  );
}
