import SearchPageLayout from "@/layouts/Search";
import Head from "next/head";

export default function SearchPage() {
  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchPageLayout />
    </div>
  );
}
