import PortfolioEdit from "@/components/portfolio/PortfolioEdit";
import EditLayout from "@/layouts/PortfolioEdit";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Edit() {
  const router = useRouter();
  const { portfolioId } = router.query;

  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EditLayout app={<PortfolioEdit portfolioId={Number(portfolioId)} />} />
    </div>
  );
}
