import Head from "next/head";
import type { GetServerSideProps } from "next";
import httpClient from "@/apis";
import { deepcopy } from "@/utils/data";
import { Member } from "@/types/member.interface";
import { usePortfolioListById } from "@/models/portfolio";
import { ProfilePagePortfolioList, ProfilePageProfile } from "@/components";
import { ProfilePageLayout } from "@/layouts";
import useUser from "@/hooks/useUser";

interface MemberIdPageProps {
  member: Member;
}

export default function Home({ member }: MemberIdPageProps) {
  const { list: portfolioList } = usePortfolioListById(member.memberId);
  const { user: userInfo } = useUser({ authorizedPage: true });

  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfilePageLayout
        profile={
          <ProfilePageProfile
            userInfo={member}
            isMypage={userInfo.memberId === member.memberId}
          />
        }
        portfiloList={
          <ProfilePagePortfolioList
            portfolioList={portfolioList}
            isMypage={userInfo.memberId === member.memberId}
          />
        }
      />
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { memberId } = context.query;
  if (Number.isNaN(Number(memberId)))
    return {
      notFound: true,
    };

  const member = (await httpClient.member.getById({ params: { id: memberId } }))
    .data;

  return {
    props: {
      member: deepcopy(member),
    },
  };
};
