import Head from "next/head";
import { MainLayout } from "@/layouts";
import MainPortfolioList from "@/components/main/MainPortfolioList";
import MainTitle from "@/components/main/MainTitle";
import MainFilter from "@/components/main/MainFilter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>BSSM SH</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout
        app={<MainPortfolioList />}
        title={<MainTitle />}
        filter={<MainFilter />}
      />
    </div>
  );
}
