import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>BSSM SH - 로그인</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>로그인 페이지 입니다.</h1>
    </div>
  );
}
